package RUfoo.managers;

public enum Channel {
	
	TREE_CHANNEL,
	
	DEFENSE_CHANNEL,
	
	ENEMY_ARCHON_CHANNEL1,
	ENEMY_ARCHON_ID_CHANNEL1,
	ENEMY_ARCHON_CHANNEL2,
	ENEMY_ARCHON_ID_CHANNEL2,
	ENEMY_ARCHON_CHANNEL3,
	ENEMY_ARCHON_ID_CHANNEL3,
	
	CENSUS_ARCHON,
	CENSUS_FIRST_ARCHON,
	CENSUS_GARDENER,
	CENSUS_FIRST_GARDENER,
	CENSUS_LUMBERJACK,
	CENSUS_FIRST_LUMBERJACK,
	CENSUS_SCOUT,
	CENSUS_FIRST_SCOUT,
	CENSUS_SOLDIER,
	CENSUS_FIRST_SOLDIER,
	CENSUS_TANK,
	CENSUS_FIRST_TANK,
}
